In [1]:
pip  install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import  numpy as np

In [3]:
a = np.arange(12)

In [4]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(12,)

In [7]:
a.shape = 3, 4

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a[2]

array([ 8,  9, 10, 11])

In [10]:
a[1, 1]

np.int64(5)

In [11]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])